---
version: "3.6"

services:
  composer:
    image: composer
    volumes:
      - "~/.composer:/tmp"
      - "./:/app"
    command: ["install", "--ignore-platform-reqs"]

  test-runner:
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - "./src:/app/src"
      - "./tests:/app/tests"
      - "./phpcs.xml.dist:/app/phpcs.xml.dist"
      - "./phpstan.neon:/app/phpstan.neon"
      - "./phpunit.xml:/app/phpunit.xml"
